### ISSUE TITLE
Can't build => can't use

### ISSUE THREAD

**Issue by p0nce** [jmdavis/dxml#11]
Using dxml v0.3.2 + DMD v2.079.1 + Windows 10

```
------ Build started: Project: dxml, Configuration: debug Win32 ------
Building lib\dxml.lib...

object.Error@(0): Access Violation
----------------
0x004156B1
0x00409F1F
0x0051251A
0x005134C5
0x005758CD
0x005A6B3B
0x0051F2C6
0x0049FF3A
0x0051E814
0x77DC58A5 in LdrQueryProcessModuleInformation
0x77DCCF4A in RtlQueryProcessDebugInformation
0x77D675B4 in RtlAllocateHeap
0x77D675FD in RtlAllocateHeap
0x006C0F60
Building lib\dxml.lib failed!
```

**Comment by jmdavis** [comment]
What's the context here? Did you just import a module from dxml and then try to build the project with dub on Windows, and you got an Access Violation when compiling? That would indicate a compiler bug rather than a bug in dxml, but either way, clear steps to reproduce it would be required. I'll try to get a Windows setup going sometime soon so that I can verify whether the unit tests work properly, but you didn't provide enough information here for me to be sure that I'm testing the same thing if I try to reproduce this.

**Comment by p0nce** [comment]
Hello,

You are right sorry. I was searching for a XML library and many were not available. The context is that I generate a VisualD project with dxml as a dependency and building.
The bug seems to be only within VisualD. Launching dub from within the command-line work.

- `dub.json`
```json
{
    "name": "bench",
    "dependencies": {      
        "dxml": "~>0.0"
    },

    "sourcePaths": ["source"],
    "importPaths": ["source"]
}
```

- `main.d`
```
void main(){}
```
This crashes the compiler, investigating...

**Comment by p0nce** [comment]
Seems to be related to JSON generation, you can have the bug without VisualD with:
```
$  dub --build=ddox
```

**Comment by p0nce** [comment]
Reduced.
The problem is that DMD chokes generating JSON with `static foreach`. Probably an old bug?
You can replace the whole dxml library with:
```d
template A(T)
{
    static foreach(i; 0..2)
    {
    }
}
```

**Comment by p0nce** [comment]
OK I just met with https://issues.dlang.org/show_bug.cgi?id=18211

**Comment by p0nce** [comment]
Conclusion: dxml need a DMDFE >= v2.081.0-beta.1

**Comment by jmdavis** [comment]
Well, at least the compiler bug has already been fixed.
