### ISSUE TITLE
stripIndent removes text

### ISSUE THREAD

**Issue by belka-ew** [jmdavis/dxml#19]
```d
unittest
{
    import dxml.util;
    import std.string;

    assert(stripIndent("foo\n      ").startsWith("foo"));
}
```

**Comment by jmdavis** [comment]
Okay. First off, the documentation says

    // If the last line is just the indent, then it and the newline before it
    // are stripped.
    assert(("    foo\n" ~
            "       bar\n" ~
            "    ").stripIndent() ==
           "foo\n" ~
           "   bar");

So, based on that, I would say that the correct behavior for `stripIndent("foo\n     ")` would be for the result to be `"foo"`, not `"foo\n"`. As such, the fix here is not correct.

Second, the test should not be its own `unittest` block. It should be with the existing tests which test both `stripIndent` and `withoutIndent`. Specifically, I'd put it on line 1227 right after this block of tests

        test!func("", "");
        test!func("     ", "");
        test!func("foo", "foo");
        test!func("\nfoo", "\nfoo");
        test!func("    foo", "foo");
        test!func("\n    foo", "foo");
        test!func("\n    foo\n", "foo");
        test!func("\n    foo\n    ", "foo");
        test!func("\n    foo\n     ", "foo\n ");

So, the new test would be

        test!func("foo\n      ", "foo");

However, with that done, the test will fail even if your fix for `stripIndent` were corrected, because `withoutIndent` still needs to be fixed. So, if you want this to be merged, then you'll need to make the test as I just showed and get it to pass (which would mean fixing your fix for `stripIndent` and adding a fix for `withoutIndent`). If you don't get to it before dconf (which is next week), then I'll try to sort this out at dconf, since I should have some time then. The fixes probably aren't hard, but I don't have time to work them out right now.
