### ISSUE TITLE
Parser fails to operate on UTF8  Files containing a BOM

### ISSUE THREAD

**Issue by cschlote** [jmdavis/dxml#25]
There seems to be a problem with UTF-8 XML files containing a BOM marker:

Parser failed with exception dxml.parser.XMLParsingException@/root/.dub/packages/dxml-0.4.3/dxml/source/dxml/parser.d(1925): [1:1]: Expected <

The problem disappeared after removing the BOM (with Geany) from the XML file, so I suppose the problem is releated to the BOM.

**Comment by jmdavis** [comment]
Sorry, for the late response, but dxml follows Phobos' approach for this by requiring that the programmer handle BOMs before doing string processing. So, if you're doing something like reading a file with `readText`, and there's a real risk of the file starting with a BOM, then you'll need to check for a BOM before passing the string to `parseXML`. std.encoding has the tools for checking for a BOM, but Phobos probably should have something added which deals with stripping it off for you so that it can be handled cleanly by programs in general.

For now, I've just updated the documentation in parser.d to mention the need to strip BOMs if present.
