### ISSUE TITLE
Change writer.output to finish()

### ISSUE THREAD

**Issue by JesseKPhillips** [jmdavis/dxml#6]
While I realize there is a slight difference in behavior/intent I think it may make sense to follow std.digest and utilize a fininsh() function rather than output() to get the output range.
https://dlang.org/phobos/std_digest_md.html

Differences:
* digest performs some actions to produce an output
* xml writer isn't changing the output nor is it providing the output result, only the original range provided.

**Comment by jmdavis** [comment]
Honestly, I think that they're so different as to be completely unrelated. I assume that you mean `finish` and not `finalize`, since only std.digest.murmurhash seems to have `finalize`, and `finalize` doesn't return anything. From what I understand, the design of std.digest is that a hash generator type is an output range, and you keep writing data to it until you've written everything that you want to hash, and then because at least some hashing algorithms need to do extra work to compute the hash once they have all the data, `finish` was introduced to provide a way to tell the output range that you're done and have it provide the final result.

What `XMLWriter.output` does is nothing like that. `XMLWriter` is not itself an output range - it uses one but isn't one - and `output` is simply a property getter for directly accessing the output range by `ref` for those cases where it's needed. In the case of `Appender`, that does mean accessing it when you're done writing the XML so that you can call `data` on it and get the underlying array (so it's similar to `finish` in the sense that in that case, it's called at the end), but in other cases, it could mean you're trying to do something like write whitespace that doesn't match the indent, because that's what's needed to get the formatting you want - or it could be anything else that it turns out you need to do that involves direct access to the output range. The `Appender` case is similar to `finish`, but IMHO, for it really to be similar, it would need to return the array from `data` rather than the output range, and that would only work if `XMLWriter` specifically used `Appender` rather than any output range of characters.

Also, there's no guarantee that someone is going to need to call `output` to access the output range. Depending on the type of the output range, simply having called `put` on it is enough, and you don't need to call anything to get at the data when you're done or to do anything else with it. However, naming the function `finish` or `finalize` would imply that you needed to call it.

Given that it's just a property getter for accessing the output range, I thought that `output` was the obvious choice. If it were actually doing something in the process, then another name might make a lot more sense, but it's just a getter.

I considered not providing access to it, but if the output range is a reference type, you have access to it anyway by virtue of having passed it to the constructor or factory function, and if it's not a reference type, and you need to do something like call `data`, then you need to be able to access it, and since `XMLWriter` works with arbitrary output ranges, we have no idea what you might actually need to call on it, meaning that giving direct access to it is the only thing that really makes sense. Maybe if `finish` were really a standard output range function (instead of just something for std.digest), and `Appender` used it, then we could go with `finish` and have it call `finish` on the underlying output range and return the result, but that was never standardized.

I also considered adding a function for writing arbitrary whitespace with the idea that it would negate a major use case for directly accessing the output range, but it wouldn't eliminate the need for it, and there might be other reasons to access it that I haven't thought of. So, I figured that I'd take the simpler approach of just letting them write to the output range directly if they wanted to write whitespace that didn't match the indent.

In any case, it doesn't seem like a good idea to me to rename `output` to anything that implies that it's anything other than a property getter as long as all it is is a property getter.

**Comment by jmdavis** [comment]
Thinking about it, I'm going to guess that what inspired this issue is the fact that `Appender` is used throughout the examples, and the only place that `output` is used there is to get at `data`. So, it does make it look a bit like it's intended specifically to work like `finish`, but that a side effect of what was needed for the examples rather than the sole purpose of `output`. I suppose that I could add some examples to `output`'s documentation to clarify it. I would have thought that `output`'s documentation would have made it clear, but reading over it now, it's mostly warning about not misusing it rather than explaining why it's there. So, I guess that it could use some improvement.

**Comment by JesseKPhillips** [comment]
Thanks, I agree and feel free to close as won't fix.
